import { CookiesProvider } from "react-cookie";
import { Footer } from "./component/navigations/Footer";
import { Navbar } from "./component/navigations/Navbar";
import "./globals.css";
import MUIProviders from "./providers/MUIProvider";

import { Rubik } from "next/font/google";
import Navigations from "./component/navigations/Navigations";
import { cookies } from "next/headers";

const rubic = Rubik({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  // subsets: ["arabic"],,
  subsets: ["latin", "arabic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const cookieStore = await cookies();
  const lng = cookieStore.get("i18next")?.value || "ar";
  return (
    <html lang={lng} dir={lng === "ar" ? "rtl" : "ltr"}>
      <body className={rubic.className}>
        <MUIProviders lng={lng}>
          <Navbar lng={lng} />

          {children}
          <Footer lng={lng} />
        </MUIProviders>
      </body>
    </html>
  );
}
