import "./globals.css";
import MUIProviders from "./providers/MUIProvider";

import { Rubik } from "next/font/google";

const rubic = Rubik({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  // subsets: ["arabic"],,
  subsets: ["latin", "arabic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const resolvedParams = await params;
  const lng = resolvedParams.lng;
  return (
    <html lang={lng} dir={lng === "ar" ? "rtl" : "ltr"}>
      <MUIProviders lng={lng}>
        <body className={rubic.className}>{children}</body>
      </MUIProviders>
    </html>
  );
}
