import "./globals.css";
import MUIProviders from "./providers/MUIProvider";

import { Noto_Kufi_Arabic } from "next/font/google";

const noto = Noto_Kufi_Arabic({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const resolvedParams = await params;
  const lng = resolvedParams.lng;
  return (
    <html lang={lng} dir={lng === "ar" ? "rtl" : "ltr"}>
      <MUIProviders lng={lng}>
        <body className={noto.className}>{children}</body>
      </MUIProviders>
    </html>
  );
}
